-- MySQL Script generated by MySQL Workbench
-- Sat Apr 13 17:24:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='';

-- -----------------------------------------------------
-- Schema bbs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bbs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bbs` DEFAULT CHARACTER SET utf8mb4 ;
USE `bbs` ;

-- -----------------------------------------------------
-- Table `bbs`.`bbs_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`bbs_user` ;

CREATE TABLE IF NOT EXISTS `bbs`.`bbs_user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL COMMENT '账号',
  `password` VARCHAR(255) NOT NULL COMMENT '密码',
  `nickname` VARCHAR(20) NULL COMMENT '昵称',
  `avatar` VARCHAR(255) NULL COMMENT '头像',
  `thread_count` INT NOT NULL DEFAULT 0 COMMENT '发帖数',
  `score` INT NOT NULL DEFAULT 0 COMMENT '积分',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态\n',
  `created_at` INT NOT NULL COMMENT '注册时间',
  `created_ip` VARCHAR(15) NOT NULL COMMENT '注册IP',
  `login_at` INT NOT NULL DEFAULT 0 COMMENT '登录时间',
  `login_ip` VARCHAR(15) NULL COMMENT '登录IP',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `bbs`.`bbs_forum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`bbs_forum` ;

CREATE TABLE IF NOT EXISTS `bbs`.`bbs_forum` (
  `forum_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(20) NOT NULL COMMENT '版块名称',
  `logo` VARCHAR(255) NOT NULL COMMENT '版块LOGO',
  `desc` VARCHAR(100) NOT NULL COMMENT '版块简介',
  `topic_count` INT NOT NULL DEFAULT 0 COMMENT '主题数',
  `thread_count` INT NOT NULL DEFAULT 0 COMMENT '帖子数',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态',
  `created_at` INT NOT NULL COMMENT '添加时间',
  PRIMARY KEY (`forum_id`),
  UNIQUE INDEX `name_UNIQUE` (`title` ASC))
ENGINE = InnoDB
COMMENT = '版块表';


-- -----------------------------------------------------
-- Table `bbs`.`bbs_topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`bbs_topic` ;

CREATE TABLE IF NOT EXISTS `bbs`.`bbs_topic` (
  `topic_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL COMMENT '标题',
  `content` TEXT NOT NULL COMMENT '帖子内容',
  `created_at` INT NOT NULL COMMENT '发布时间',
  `updated_at` INT NOT NULL DEFAULT 0 COMMENT '最后编辑时间',
  `deleted_at` INT NOT NULL DEFAULT 0 COMMENT '删除时间',
  `flag` TINYINT NOT NULL DEFAULT 0 COMMENT '标志位(回复可见,精华)',
  `top` TINYINT NOT NULL DEFAULT 0 COMMENT '置顶',
  `reply_count` INT NOT NULL DEFAULT 0 COMMENT '回复数量',
  `view_count` INT NOT NULL DEFAULT 0 COMMENT '查看数量',
  `favorite_count` INT NOT NULL DEFAULT 0 COMMENT '收藏数量',
  `forum_id` INT UNSIGNED NOT NULL COMMENT '版块ID',
  `user_id` INT UNSIGNED NOT NULL COMMENT '发帖人ID',
  PRIMARY KEY (`topic_id`),
  INDEX `fk_bbs_topic_bbs_forum1_idx` (`forum_id` ASC),
  INDEX `fk_bbs_topic_bbs_user1_idx` (`user_id` ASC))
ENGINE = InnoDB
COMMENT = '主题表';


-- -----------------------------------------------------
-- Table `bbs`.`bbs_reply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`bbs_reply` ;

CREATE TABLE IF NOT EXISTS `bbs`.`bbs_reply` (
  `reply_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL COMMENT '回复内容',
  `created_at` INT NOT NULL COMMENT '回复时间',
  `updated_at` INT NOT NULL DEFAULT 0 COMMENT '最后编辑时间',
  `deleted_at` INT NOT NULL DEFAULT 0 COMMENT '删除时间',
  `topic_id` INT UNSIGNED NOT NULL,
  `forum_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`reply_id`),
  INDEX `fk_bbs_thread_bbs_topic1_idx` (`topic_id` ASC),
  INDEX `fk_bbs_thread_bbs_forum1_idx` (`forum_id` ASC),
  INDEX `fk_bbs_thread_bbs_user1_idx` (`user_id` ASC))
ENGINE = InnoDB
COMMENT = '回帖表';


-- -----------------------------------------------------
-- Table `bbs`.`bbs_favorite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`bbs_favorite` ;

CREATE TABLE IF NOT EXISTS `bbs`.`bbs_favorite` (
  `user_id` INT UNSIGNED NOT NULL COMMENT '用户ID',
  `topic_id` INT UNSIGNED NOT NULL COMMENT '帖子ID',
  `created_at` INT NOT NULL COMMENT '收藏时间',
  PRIMARY KEY (`user_id`, `topic_id`),
  INDEX `fk_bbs_favorite_bbs_topic1_idx` (`topic_id` ASC))
ENGINE = InnoDB
COMMENT = '收藏表';


-- -----------------------------------------------------
-- Table `bbs`.`bbs_forum_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`bbs_forum_admin` ;

CREATE TABLE IF NOT EXISTS `bbs`.`bbs_forum_admin` (
  `user_id` INT UNSIGNED NOT NULL,
  `forum_id` INT UNSIGNED NOT NULL,
  `created_at` INT NOT NULL COMMENT '任职时间',
  `expired_at` INT NOT NULL COMMENT '过期时间',
  PRIMARY KEY (`user_id`, `forum_id`),
  INDEX `fk_bbs_forum_admin_bbs_forum1_idx` (`forum_id` ASC))
ENGINE = InnoDB
COMMENT = '版主表';


-- -----------------------------------------------------
-- Table `bbs`.`bbs_topic_score_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`bbs_topic_score_log` ;

CREATE TABLE IF NOT EXISTS `bbs`.`bbs_topic_score_log` (
  `log_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `score` TINYINT NOT NULL COMMENT '积分变动',
  `msg` VARCHAR(40) NOT NULL COMMENT '变动消息',
  `created_at` INT NOT NULL COMMENT '操作时间',
  `topic_id` INT UNSIGNED NOT NULL COMMENT '主题ID',
  `user_id` INT UNSIGNED NOT NULL COMMENT '版主ID',
  PRIMARY KEY (`log_id`),
  INDEX `fk_bbs_topic_score_log_bbs_topic1_idx` (`topic_id` ASC),
  INDEX `fk_bbs_topic_score_log_bbs_user1_idx` (`user_id` ASC))
ENGINE = InnoDB
COMMENT = '帖子积分表';


-- -----------------------------------------------------
-- Table `bbs`.`bbs_user_score_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`bbs_user_score_log` ;

CREATE TABLE IF NOT EXISTS `bbs`.`bbs_user_score_log` (
  `log_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `score` TINYINT NOT NULL COMMENT '积分变动',
  `remain` INT NOT NULL COMMENT '剩余积分',
  `msg` VARCHAR(40) NOT NULL COMMENT '变动原因',
  `created_at` INT NOT NULL COMMENT '变动时间',
  `user_id` INT UNSIGNED NOT NULL COMMENT '用户ID',
  PRIMARY KEY (`log_id`),
  INDEX `fk_bbs_user_score_log_bbs_user1_idx` (`user_id` ASC))
ENGINE = InnoDB
COMMENT = '用户积分表';


-- -----------------------------------------------------
-- Table `bbs`.`bbs_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`bbs_admin` ;

CREATE TABLE IF NOT EXISTS `bbs`.`bbs_admin` (
  `admin_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL COMMENT '账号',
  `password` VARCHAR(255) NOT NULL COMMENT '密码',
  `created_at` INT NOT NULL COMMENT '注册时间',
  `login_at` INT NOT NULL DEFAULT 0 COMMENT '登录时间',
  `login_ip` VARCHAR(15) NULL COMMENT '登录IP',
  PRIMARY KEY (`admin_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
